[phases.setup]
nixPkgs = [
    "stdenv",
    "gcc",
    "postgresql",
    "zlib"
]

[phases.build]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn a_core.wsgi" 