[phases.setup]
nixPkgs = [
    "stdenv",
    "gcc",
    "postgresql",
    "zlib",
    "python3",
    "python3Packages.pip"
]

[env]
PYTHON_VERSION = "3"
VIRTUAL_ENV = "/opt/venv"
PATH = "/opt/venv/bin:$PATH"
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "a_core.settings"
PORT = "8080"

[phases.build]
cmds = [
    "rm -rf /opt/venv || true",
    "python3 -m venv /opt/venv",
    "pip install --no-cache-dir -r requirements.txt",
    "python3 manage.py collectstatic --noinput || true"
]

[start]
cmd = "cd /mysite && gunicorn a_core.wsgi:application --bind 0.0.0.0:${PORT:-8080}" 