[phases.setup]
nixPkgs = [
    "stdenv",
    "gcc",
    "postgresql",
    "zlib",
    "python3",
    "python3Packages.pip"
]

[env]
PYTHON_VERSION = "3"
VIRTUAL_ENV = "/opt/venv"
PATH = "/opt/venv/bin:$PATH"

[phases.build]
cmds = [
    "rm -rf /opt/venv || true",
    "python3 -m venv /opt/venv",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn a_core.wsgi" 