[phases.setup]
nixPkgs = [
    "stdenv",
    "gcc",
    "postgresql",
    "zlib",
    "python3",
    "python3Packages.pip"
]

[env]
PYTHON_VERSION = "3"

[phases.build]
cmds = [
    "which python3 > /tmp/python_path && $(cat /tmp/python_path) -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn a_core.wsgi" 