# Generated by Django 5.1.4 on 2025-01-06 10:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_navigationsettings'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('mastodon_url', models.URLField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Settings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='locale',
        ),
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
