# Generated by Django 5.1.4 on 2025-01-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_newsindexpage_articlepage_articlepagetag_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsIndexPage',
            new_name='NewsPage',
        ),
    ]
